### ISSUE TITLE
Home Assistant refuses to restart because of IntesisBox 

### ISSUE THREAD

**Issue by Glirido** [jnimmo/hass-intesisbox#47]
After updating HA to version 2023.6.3 from version 2023.3.6 the integration starts to fail.

These are the results of my tryings:

- HA 2023.3.6 + IntesisBox  b87373e --> Working fine.
- HA 2023.6.3 + IntesisBox  b87373e --> Not loading integration but yes HA. No logs from this combo but i think is related to https://github.com/jnimmo/hass-intesisbox/pull/33
- HA 2023.6.3 + IntesisBox  4fca996 --> HA refuse to restart. See attached logs.

I have gone backwards to initial setup and things starts to work again.

```
2023-07-04 17:25:21.197 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration intesisbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 17:25:22.764 ERROR (MainThread) [homeassistant.config] Platform error: climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/intesisbox/climate.py", line 37, in <module>
    from homeassistant.helpers.typing import ConfigEntry, ConfigType, DiscoveryInfoType
ImportError: cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
2023-07-04 17:25:23.184 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform intesisbox.climate: Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)).
2023-07-04 17:25:27.279 WARNING (MainThread) [homeassistant.components.aemet.weather_update_coordinator] Station data is outdated
2023-07-04 17:26:28.579 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Platform error climate.intesisbox - cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
2023-07-04 17:26:28.582 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140132274453584] The system cannot restart because the configuration is not valid: Platform error climate.intesisbox - cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 887, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 181, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.intesisbox - cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
```

**Comment by skellycode** [comment]
+1
I have this same issue.

`cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing'`

**Comment by joaomoreira-obvio** [comment]
@Glirido yes, seems like the same, sorry for the duplicate.

**Comment by joaomoreira-obvio** [comment]
Hello @Glirido any update on this issue?
Thanks

**Comment by joaomoreira-obvio** [comment]
Do you I need help? Or may I help in any way?
This is plug in was really useful for me :)

**Comment by wisey18** [comment]
Version 2.0 of Intensisbox seems to be broke with version 2023.11.3. The integration fails to load. I reverted back to version 1.3.4 of intensisbox and all is working now.

**Comment by Glirido** [comment]
I dont find any version 1.3.4 of intesisbox. Which one are you referring to?
In github there is only versions 0.99, 1.0.0 and 2.0.0.
Thanks!

**Comment by skellycode** [comment]
Has anyone tested version 2.0.0 with HA 2023.12.0?
My setup is currently working with version 2.0.0 on 2023.11.1, but am hesitant to upgrade given that a problem appears to have been introduced in 2023.11.3 based on the comments above

**Comment by Glirido** [comment]
I have done several tests and it seems that version 2.0.0 works OK with latest 2023.12.4.
Also works with 2023.11.2 and 2023.11.3. 
I have done all the tests in fresh docker installations. So i don't know if migrating from previous versions could be a problem.

Bisecting with GIT i've got this:

> ```
> f7150d7930961ff02cd1cdd6a79f21879b742d23 is the first bad commit
> commit f7150d7930961ff02cd1cdd6a79f21879b742d23
> Author: Jonas Bergler <jonas@bergler.name>
> Date:   Thu Mar 30 20:48:44 2023 +1300
> 
>     make linters happy
> 
> ```

Log shows this error from that commit onwards:

> `2024-01-03 14:47:06.863 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'intesisbox.climate': Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py))`

**Comment by skellycode** [comment]
Have updated to 2024.1.0 and version 2.0.0 works as per normal.  Looks like it's just the latest commit (as mentioned by @Glirido above) that is broken.

**Comment by joaomoreira-obvio** [comment]
@Glirido I can confirm it's working now.
Thank you very much

**Comment by luismalddonado** [comment]
I just created a fork of this project fixing the issue (https://github.com/luismalddonado/hass-intesisbox/tree/main).
But my intention is just help a little bit. This repository is great and  I do not want to maintain a different repository. If @jnimmo wants to apply this changes here would be great for all of us

**Comment by Glirido** [comment]
Fantastic @luismalddonado.
Maybe you should open a PR with your changes.

**Comment by jnimmo** [comment]
Nice work on coming up with a fix- open up a pull request I'd be very happy to merge the changes, thank you

**Comment by luismalddonado** [comment]
> Nice work on coming up with a fix- open up a pull request I'd be very happy to merge the changes, thank you

Hi. I was not able to open a pull request as I was not able to push a new branch.

lgarrido@raspberrypi:~/XXX/hass-intesisbox $ git push -u origin fixes
ERROR: Permission to jnimmo/hass-intesisbox.git denied to luismalddonado.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

**Comment by Glirido** [comment]
Its not required to have rights to create a PR.
Yo can do it from your own fork: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by luismalddonado** [comment]
ok. Done!!

**Comment by skellycode** [comment]
This can now be closed with the latest update @jnimmo @Glirido

**Comment by luismalddonado** [comment]
In version [v2.0.1] this should be fixed now
