### ISSUE TITLE
Add-On Failed to Setup since HA 2023.5 update

### ISSUE THREAD

**Issue by warwickofthegh** [jnimmo/hass-intesisbox#43]
Ever since updating HA to 2023.5 the add-on fails to setup with error logs below. My device on 192.168.1.48 is available on the local network, nothing I can think of has changed other than the HA version. Is it just me or others seeing this?

------

ERROR:
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/intesisbox/__init__.py:29
Integration: IntesisBox ([documentation](https://github.com/jnimmo/hass-intesisbox))
First occurred: May 10, 2023 at 5:56:00 PM (1 occurrences)
Last logged: May 10, 2023 at 5:56:00 PM

Error setting up entry 192.168.1.48 for intesisbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/intesisbox/__init__.py", line 29, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

---------

WARNING:
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for intesisbox doing blocking calls at custom_components/intesisbox/intesisbox.py, line 73: sleep(1)

**Comment by warwickofthegh** [comment]
Looks like this was introduced by HA now blocking this usage of async_setup_platforms as stated in this other message 

_Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for enphase_envoy using this method at custom_components/enphase_envoy/init.py, line 131: hass.config_entries.async_setup_platforms(entry, PLATFORMS)_

**Comment by segalles** [comment]
Hello, the last version does not have this error. I upgrade and the problem is solved.

**Comment by warwickofthegh** [comment]
> Hello, the last version does not have this error. I upgrade and the problem is solved.

The last version was release a few months ago (v2) , I've just tried to recopy this latest version and it still has the invalid code which Home Assistant now blocks from loading.

I still get this error:

_Logger: homeassistant.setup
Source: setup.py:348
First occurred: 10:10:20 PM (1 occurrences)
Last logged: 10:10:20 PM

Unable to prepare setup for platform intesisbox.climate: Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py))._

@segalles can you confirm which version of Home Assistant you are running?

**Comment by tathamoddie** [comment]
This was already fixed in v1.0.0 of this integration:

https://github.com/jnimmo/hass-intesisbox/releases/tag/v1.0.0

Fixed by PR #33

Tested and working fine on my local HA, 2023.5.4.

**Comment by tathamoddie** [comment]
The original issue at the top of this thread was fixed by #33, included in https://github.com/jnimmo/hass-intesisbox/releases/tag/v1.0.0

I'm running v2.0.0 on HA 2023.5.4 and everything is smooth.

It sounds like you're copying stuff in to place manually. Try using HACS for a more controlled install experience, and access to an easy update button.

https://hacs.xyz/

**Comment by warwickofthegh** [comment]
thanks for the reply @tathamoddie - loaded via hacs and it all works now, must have been a cache issue.

**Comment by tathamoddie** [comment]
Glad to hear that it's now working for you. 👍
